#!/usr/bin/env python3
"""Test script to verify timer app generation works"""

import requests
import json
import time

# Test basic timer app generation
def test_timer_app():
    print("Testing Timer App Generation...")
    
    url = "http://localhost:8000/api/generate"
    
    payload = {
        "description": "Create a simple timer app with start, stop, and reset buttons. Use modern SwiftUI design.",
        "app_name": "SimpleTimer"
    }
    
    try:
        response = requests.post(url, json=payload, timeout=120)
        
        if response.status_code == 200:
            result = response.json()
            print(f"✅ SUCCESS: {result.get('message', 'App generated')}")
            print(f"Project ID: {result.get('project_id')}")
            print(f"Generated by: {result.get('generated_by', 'Unknown')}")
            return True
        else:
            print(f"❌ FAILED: Status {response.status_code}")
            print(f"Error: {response.text}")
            return False
            
    except Exception as e:
        print(f"❌ ERROR: {str(e)}")
        return False

if __name__ == "__main__":
    # Wait a moment for server to be ready
    time.sleep(2)
    
    # Run the test
    success = test_timer_app()
    
    if success:
        print("\n✅ Timer app test passed!")
    else:
        print("\n❌ Timer app test failed!")